### ISSUE TITLE
Stacktrace in 2024.1

### ISSUE THREAD

**Issue by flyhard** [ricemery/Assertions2AssertJ#15]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.chainstaysoftware.testing.FileAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.chainstaysoftware.assertions2assertj]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

**Comment by ricemery** [comment]
Thank you for the report. Reproduce the problem on 2024.1 as well.
I'll investigate a fix.

**Comment by ricemery** [comment]
Fixed. Thanks @flyhard!
